core/urls.py
"""Importaciones de módulos de Django"""

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

# Definición de las URLs del proyecto
urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "home/", TemplateView.as_view(template_name="pages/core/home.html"), name="home"
    ),
    path("", include(("products.urls", "products"))),
    path("users/", include(("users.urls", "users"))),
]


# Configuración para servir archivos estáticos durante el desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
"""Importaciones necesarias para las URLs"""

# Importa la función path para definir rutas en la aplicación
from django.urls import path

# Importa las vistas necesarias para las rutas de autenticación
from .views import (
    LoginView,  # Vista para el inicio de sesión
    RegisterView,  # Vista para el registro de nuevos usuarios
    LogoutView,  # Vista para el cierre de sesión
    UserChangeInfoView,
)

# Define las rutas URL para las vistas de autenticación
urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("edit/", UserChangeInfoView.as_view(), name="edit"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

users/forms.py
"""Importaciones necesarias para los formularios"""

# Importa el módulo forms de Django para la creación de formularios
from django import forms

# Importa formularios específicos para la creación y autenticación de usuarios,
# así como el modelo de usuario
from django.contrib.auth.forms import (
    UserCreationForm,  # Formulario para el registro de nuevos usuarios
    AuthenticationForm,  # Formulario para la autenticación de usuarios
    User,  # Modelo de usuario de Django
)

# Importa ValidationError que se utiliza para lanzar excepciones de Validación.
from django.core.exceptions import ValidationError

# Importa validate_password verificar politicas de seguridad contraseñas.
from django.contrib.auth.password_validation import validate_password


class RegisterUserForm(UserCreationForm):
    """
    Formulario para el registro de nuevos usuarios.

    Hereda de UserCreationForm e incluye los campos para el nombre de usuario
    y las contraseñas (password1 y password2). Los mensajes de ayuda para los
    campos están vacíos.
    """

    class Meta:
        """
        Clase interna que proporciona metainformación sobre el formulario.

        Define el modelo asociado al formulario y los campos que deben
        incluirse en el formulario. Los mensajes de ayuda para los campos
        están configurados para no mostrar ningún texto adicional.
        """

        model = User
        fields = ["username", "password1", "password2"]
        help_texts = {k: "" for k in fields}


class LoginUserForm(AuthenticationForm):
    """
    Formulario para la autenticación de usuarios existentes.

    Hereda de AuthenticationForm e incluye los campos para el nombre de usuario
    y la contraseña.
    """

    class Meta:
        """
        Clase interna que proporciona metainformación sobre el formulario.

        Define el modelo asociado al formulario y los campos que deben
        incluirse en el formulario. No se configuran mensajes de ayuda para los
        campos en este formulario.
        """

        model = User
        fields = ["username", "password"]


class UserChangeInfoForm(forms.ModelForm):
    """
    Un formulario para cambiar la información del usuario y actualizar la contraseña.

    Campos del formulario:
    - username: Nombre de usuario (opcional, mínimo 3 caracteres).
    - email: Dirección de correo electrónico (requerido).
    - current_password: Contraseña actual (requerida, mínimo 8 caracteres).
    - password_new: Nueva contraseña (opcional, mínimo 8 caracteres).
    - password_new_confirm: Confirmación de la nueva contraseña (opcional, mínimo 8 caracteres).
    """

    username = forms.CharField(min_length=3, required=False)
    email = forms.EmailField()
    current_password = forms.CharField(widget=forms.PasswordInput(), min_length=8)
    password_new = forms.CharField(
        widget=forms.PasswordInput(), required=False, min_length=8
    )
    password_new_confirm = forms.CharField(
        widget=forms.PasswordInput(), required=False, min_length=8
    )

    class Meta:
        """
        Metadatos para el formulario UserChangeInfoForm.

        Atributos:
        - model: El modelo asociado con este formulario. En este caso, el modelo User.
        - fields: Lista de campos del modelo que se incluyen en el formulario.
                Incluye 'username', 'email', 'password_new',
                'current_password', y 'password_new_confirm'.
        - help_texts: Diccionario para proporcionar textos de ayuda adicionales para los campos
                    del formulario. En este caso, todos los textos de ayuda se establecen
                    como cadenas vacías.
        """

        model = User
        fields = [
            "username",
            "email",
            "password_new",
            "current_password",
            "password_new_confirm",
        ]
        help_texts = {k: "" for k in fields}

    def __init__(self, *args, **kwargs):
        """
        Inicializa el formulario y extrae el usuario actual de los argumentos.

        :param args: Argumentos posicionales.
        :param kwargs: Argumentos de palabra clave, se espera que
                    'current_user' sea uno de ellos.
        """
        self.current_user = kwargs.pop("current_user", None)
        super().__init__(*args, **kwargs)

    def clean_username(self):
        """
        Valida el campo de nombre de usuario para asegurarse de que no
        esté en uso por otro usuario.

        :raises ValidationError: Si el nombre de usuario ya está en uso.
        :return: El nombre de usuario limpio.
        """
        username = self.cleaned_data.get("username")
        if username and username != self.current_user.username:
            if (
                User.objects.exclude(pk=self.current_user.pk)
                .filter(username=username)
                .exists()
            ):
                raise ValidationError("El nombre de usuario ya está en uso.")
        return username

    def clean(self):
        """
        Valida los campos del formulario, incluyendo la coincidencia de las contraseñas
        y la validez de la nueva contraseña.

        :return: Los datos limpios del formulario.
        """
        cleaned_data = super().clean()
        password_new = cleaned_data.get("password_new")
        password_new_confirm = cleaned_data.get("password_new_confirm")
        if password_new or password_new_confirm:
            if not password_new:
                self.add_error(
                    "password_new", "Debes proporcionar la nueva contraseña."
                )
            if not password_new_confirm:
                self.add_error(
                    "password_new_confirm", "Debes confirmar la nueva contraseña."
                )
            if (
                password_new
                and password_new_confirm
                and password_new != password_new_confirm
            ):
                self.add_error("password_new_confirm", "Las contraseñas no coinciden.")
            if password_new:
                try:
                    validate_password(password_new)
                except ValidationError as e:
                    self.add_error("password_new", e)
        return cleaned_data

users/views.py
"""Importaciones necesarias para la vista de inicio de sesión"""

# Importa funciones para renderizar plantillas y redirigir a otras vistas
from django.shortcuts import render, redirect

# Importa la clase base para vistas basadas en clases
from django.views import View

# Importa mixins para requerir autenticación de usuarios
from django.contrib.auth.mixins import LoginRequiredMixin

# Importa funciones para manejar la autenticación de usuarios
from django.contrib.auth import login, logout

# Importa el módulo para mostrar mensajes de usuario
from django.contrib import messages

# Importa `authenticate` y `update_session_auth_hash` para gestionar la autenticación del usuario.
from django.contrib.auth import authenticate, update_session_auth_hash

# Importa los formularios personalizados para el registro y el inicio de sesión de usuarios
from .forms import RegisterUserForm, LoginUserForm, UserChangeInfoForm


class LoginView(View):
    """
    Vista para gestionar el inicio de sesión de los usuarios.
    """

    def get(self, request):
        """
        Muestra el formulario de inicio de sesión.

        Parámetros:
        - request: Objeto HttpRequest que contiene datos de la solicitud.

        Retorna:
        - Renderiza la plantilla de inicio de sesión con un formulario vacío.
        """
        return render(
            request, "pages/users/login.html", context={"form": LoginUserForm}
        )

    def post(self, request):
        """
        Procesa el formulario de inicio de sesión y autentica al usuario.

        Parámetros:
        - request: Objeto HttpRequest que contiene los datos del formulario.

        Retorna:
        - Redirige a la página de productos si el inicio de sesión es exitoso.
        - Renderiza nuevamente el formulario de inicio de sesión con mensajes de
        advertencia si los datos son inválidos.
        """
        form = LoginUserForm(request, request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("products:sale_products")

        messages.warning(request, "El usuario o la contraseña no son válidos!")
        return render(request, "pages/users/login.html", context={"form": form})


class RegisterView(View):
    """
    Vista para gestionar el registro de nuevos usuarios.
    """

    def get(self, request):
        """
        Muestra el formulario de registro de usuario.

        Parámetros:
        - request: Objeto HttpRequest que contiene datos de la solicitud.

        Retorna:
        - Renderiza la plantilla de registro con un formulario vacío.
        """
        return render(
            request, "pages/users/register.html", context={"form": RegisterUserForm}
        )

    def post(self, request):
        """
        Procesa el formulario de registro y crea un nuevo usuario.

        Parámetros:
        - request: Objeto HttpRequest que contiene los datos del formulario.

        Retorna:
        - Redirige a la página de productos si el registro es exitoso y
        el usuario inicia sesión automáticamente.
        - Renderiza nuevamente el formulario de registro con los errores si los datos son inválidos.
        """
        form = RegisterUserForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Usuario registrado correctamente!")
            return redirect("products:sale_products")

        return render(request, "pages/users/register.html", context={"form": form})


class UserChangeInfoView(LoginRequiredMixin, View):
    """
    Vista para gestionar la actualización de la información del usuario.

    Esta vista permite a los usuarios cambiar su nombre de usuario, dirección
    de correo electrónico y contraseña.
    """

    def get(self, request):
        """
        Muestra el formulario de actualización de usuario.

        Este método maneja las solicitudes GET y renderiza el formulario para que
        el usuario pueda ingresar los datos que desea actualizar.

        Parámetros:
        - request: Objeto HttpRequest que contiene datos de la solicitud.

        Retorna:
        - Renderiza la plantilla de actualización de usuario con un formulario vacío o
        prellenado con los datos actuales.
        """
        form = UserChangeInfoForm(instance=request.user, current_user=request.user)
        return render(request, "pages/users/change.html", context={"form": form})

    def post(self, request):
        """
        Procesa el formulario de actualización de usuario.

        Este método maneja las solicitudes POST, valida el formulario y actualiza
        la información del usuario si los datos son válidos. También maneja la autenticación
        de la contraseña actual antes de realizar cambios en la cuenta del usuario.

        Parámetros:
        - request: Objeto HttpRequest que contiene datos de la solicitud, incluyendo los
        datos del formulario.

        Retorna:
        - Si el formulario es válido y la contraseña actual es correcta:
          Redirige al usuario con un mensaje de éxito.
        - Si la contraseña actual no es correcta:
          Redirige al usuario con un mensaje de error.
        - Si el formulario no es válido:
          Renderiza la plantilla de actualización con el formulario y los errores.
        """
        current_username = request.user.username
        form = UserChangeInfoForm(
            request.POST, instance=request.user, current_user=request.user
        )
        if form.is_valid():
            current_password = form.cleaned_data.get("current_password")
            new_username = form.cleaned_data.get("username")
            new_email = form.cleaned_data.get("email")
            new_password = form.cleaned_data.get("password_new")
            user = authenticate(username=current_username, password=current_password)
            if user is not None:
                if new_username and new_username != request.user.username:
                    request.user.username = new_username
                if new_email and new_email != request.user.email:
                    request.user.email = new_email
                if new_password:
                    request.user.set_password(new_password)
                    update_session_auth_hash(request, request.user)
                request.user.save()
                messages.success(request, "Usuario actualizado correctamente!")
                return redirect("users:edit")
            else:
                messages.error(request, "La contraseña actual no es correcta!")
                return redirect("users:edit")
        return render(request, "pages/users/change.html", context={"form": form})


class LogoutView(LoginRequiredMixin, View):
    """
    Vista para gestionar el cierre de sesión de los usuarios.
    """

    def get(self, request):
        """
        Cierra la sesión del usuario y redirige a la página de inicio.

        Parámetros:
        - request: Objeto HttpRequest que contiene datos de la solicitud.

        Retorna:
        - Redirige al usuario a la página de inicio después de cerrar la sesión.
        """
        logout(request)
        return redirect("home")

templates/pages/users/change.html
{% extends 'components/container.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Profile{% endblock title %}

{% block container %}

<div class="w-[80%] mx-auto">
    <form class=" flex gap-x-16 px-4 md:px-8 max-w-4xl mx-auto py-4" method="post">
        {% csrf_token %}
        <div class="w-full">
            <h2 class="text-base font-semibold leading-7 text-gray-900">Actualizar Información del Usuario</h2>
            <p class="mt-1 text-sm leading-6 text-gray-600">Modifica tu información de perfil aquí.</p>

            <!-- Username Field -->
            <div class="mt-4">
                <label for="id_username" class="block text-sm font-medium leading-6 text-gray-900">Nombre de usuario</label>
                <div class="mt-2">
                    {% for error in form.username.errors %}
                    <div class="text-xs text-red-700 font-medium">
                        <span>{{ error }}</span><br>
                    </div>
                    {% endfor %}
                    <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-indigo-600 sm:max-w-md">
                        {{ form.username|add_class:"block flex-1 border-0 bg-transparent py-1.5 pl-2 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" }}
                    </div>
                </div>
            </div>

            <!-- Email Field -->
            <div class="mt-4">
                <label for="id_email" class="block text-sm font-medium leading-6 text-gray-900">Correo electrónico</label>
                <div class="mt-2">
                    {% for error in form.email.errors %}
                    <div class="text-xs text-red-700 font-medium">
                        <span>{{ error }}</span><br>
                    </div>
                    {% endfor %}
                    <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-indigo-600 sm:max-w-md">
                        {{ form.email|add_class:"block flex-1 border-0 bg-transparent py-1.5 pl-2 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6"|attr:"placeholder=ejemplo@gmail.com" }}
                    </div>
                </div>
            </div>

            <!-- Current Password Field -->
            <div class="my-4">
                <label for="id_current_password" class="block text-sm font-medium leading-6 text-gray-900">Contraseña actual</label>
                <div class="mt-2">
                    {% for error in form.current_password.errors %}
                    <div class="text-xs text-red-700 font-medium">
                        <span>{{ error }}</span><br>
                    </div>
                    {% endfor %}
                    <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-indigo-600 sm:max-w-md">
                        {{ form.current_password|add_class:"block flex-1 border-0 bg-transparent py-1.5 pl-2 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" }}
                    </div>
                </div>
            </div>

            <!-- New Password Field -->
            <div class="my-4">
                <label for="id_password_new" class="block text-sm font-medium leading-6 text-gray-900">Nueva contraseña</label>
                <div class="mt-2">
                    {% for error in form.password_new.errors %}
                    <div class="text-xs text-red-700 font-medium">
                        <span>{{ error }}</span><br>
                    </div>
                    {% endfor %}
                    <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-indigo-600 sm:max-w-md">
                        {{ form.password_new|add_class:"block flex-1 border-0 bg-transparent py-1.5 pl-2 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" }}
                    </div>
                </div>
            </div>

            <!-- Confirm New Password Field -->
            <div class="my-4">
                <label for="id_password_new_confirm" class="block text-sm font-medium leading-6 text-gray-900">Confirmar nueva contraseña</label>
                <div class="mt-2">
                    {% for error in form.password_new_confirm.errors %}
                    <div class="text-xs text-red-700 font-medium">
                        <span>{{ error }}</span><br>
                    </div>
                    {% endfor %}
                    <div class="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 focus-within:ring-2 focus-within:ring-indigo-600 sm:max-w-md">
                        {{ form.password_new_confirm|add_class:"block flex-1 border-0 bg-transparent py-1.5 pl-2 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm sm:leading-6" }}
                    </div>
                </div>
            </div>

            <!-- Submit Button and Cancel Link -->
            <div class="mt-4 flex items-center justify-end gap-x-6">
                <a href="{% url 'products:sale_products' %}" class="text-sm font-semibold leading-6 text-gray-900">Cancelar</a>
                <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Guardar cambios</button>
            </div>
        </div>

        <div class="lg:block hidden  lg:h-[400px] md:h-[600px] lg:mt-10">
            <img src="{% static 'images/login.png' %}" class="w-full h-full max-md:w-5/6 mx-auto block object-cover" alt="Dining Experience" />
        </div>
    </form>
</div>

{% endblock container %}

templates/pages/users/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}

  <div class="font-[sans-serif]">
    <div class="min-h-screen flex fle-col items-center justify-center py-6 px-4">
      <div class="grid md:grid-cols-2 items-center gap-4 max-w-6xl w-full">
        <div class="border border-gray-300 rounded-lg p-6 max-w-md shadow-[0_2px_22px_-4px_rgba(93,96,127,0.2)] max-md:mx-auto">
          <form class="space-y-4" method="POST">
            {% csrf_token %}
            <div class="mb-8">
              <h3 class="text-gray-800 text-3xl font-extrabold">Ingresa a tu Cuenta</h3>
            </div>

            <div>
              <label for="id_username" class="text-gray-800 text-sm mb-2 block">Usuario</label>
              <div class="relative flex items-center">
                {% for error in form.username.errors %}
                  <div class="text-xs text-red-700 font-medium block">
                      <span>{{ error }}</span><br>
                  </div>
                {% endfor %}
                {{ form.username|add_class:"w-full text-sm text-gray-800 border border-gray-300 px-4 py-3 rounded-lg outline-blue-600" }}
                {% comment %} <svg xmlns="http://www.w3.org/2000/svg" fill="#bbb" stroke="#bbb" class="w-[18px] h-[18px] absolute right-4" viewBox="0 0 24 24">
                  <circle cx="10" cy="7" r="6" data-original="#000000"></circle>
                  <path d="M14 15H6a5 5 0 0 0-5 5 3 3 0 0 0 3 3h12a3 3 0 0 0 3-3 5 5 0 0 0-5-5zm8-4h-2.59l.3-.29a1 1 0 0 0-1.42-1.42l-2 2a1 1 0 0 0 0 1.42l2 2a1 1 0 0 0 1.42 0 1 1 0 0 0 0-1.42l-.3-.29H22a1 1 0 0 0 0-2z" data-original="#000000"></path>
                </svg> {% endcomment %}
              </div>
            </div>
            <div>
              <label for="id_password" class="text-gray-800 text-sm mb-2 block">Contraseña</label>
              <div class="relative flex items-center">
                {% for error in form.password.errors %}
                  <div class="text-xs text-red-700 font-medium block">
                      <span>{{ error }}</span><br>
                  </div>
                {% endfor %}
                {{ form.password|add_class:"w-full text-sm text-gray-800 border border-gray-300 px-4 py-3 rounded-lg outline-blue-600" }}
                {% comment %} <svg xmlns="http://www.w3.org/2000/svg" fill="#bbb" stroke="#bbb" class="w-[18px] h-[18px] absolute right-4 cursor-pointer" viewBox="0 0 128 128">
                  <path d="M64 104C22.127 104 1.367 67.496.504 65.943a4 4 0 0 1 0-3.887C1.367 60.504 22.127 24 64 24s62.633 36.504 63.496 38.057a4 4 0 0 1 0 3.887C126.633 67.496 105.873 104 64 104zM8.707 63.994C13.465 71.205 32.146 96 64 96c31.955 0 50.553-24.775 55.293-31.994C114.535 56.795 95.854 32 64 32 32.045 32 13.447 56.775 8.707 63.994zM64 88c-13.234 0-24-10.766-24-24s10.766-24 24-24 24 10.766 24 24-10.766 24-24 24zm0-40c-8.822 0-16 7.178-16 16s7.178 16 16 16 16-7.178 16-16-7.178-16-16-16z" data-original="#000000"></path>
                </svg> {% endcomment %}
              </div>
            </div>

            {% comment %} <div class="flex flex-wrap items-center justify-between gap-4">
              <div class="flex items-center">
                <input id="remember-me" name="remember-me" type="checkbox" class="h-4 w-4 shrink-0 text-blue-600 focus:ring-blue-500 border-gray-300 rounded" />
                <label for="remember-me" class="ml-3 block text-sm text-gray-800">
                  Remember me
                </label>
              </div>

              <div class="text-sm">
                <a href="jajvascript:void(0);" class="text-blue-600 hover:underline font-semibold">
                  Forgot your password?
                </a>
              </div>
            </div> {% endcomment %}

            <div class="!mt-8">
              <button type="submit" class="w-full shadow-xl py-3 px-4 text-sm tracking-wide rounded-lg text-white bg-blue-600 hover:bg-blue-700 focus:outline-none">
                Iniciar Sesión
              </button>
            </div>

            <p class="text-sm !mt-8 text-center text-gray-800">No tienes cuenta? <a href="{% url 'users:register' %}" class="text-blue-600 font-semibold hover:underline ml-1 whitespace-nowrap">Registrar</a></p>
          </form>
        </div>
        <div class="md:block hidden  lg:h-[400px] md:h-[300px] max-md:mt-8">
          <img src="{% static 'images/login.png' %}" class="w-full h-full max-md:w-4/5 mx-auto block object-cover" alt="Dining Experience" />
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/pages/users/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Registro{% endblock title %}

{% block content %}

  <div class="font-[sans-serif]">
    <div class="min-h-screen flex fle-col items-center justify-center py-6 px-4">
      <div class="grid md:grid-cols-2 items-center gap-4 max-w-6xl w-full">
        <div class="border border-gray-300 rounded-lg p-6 max-w-md shadow-[0_2px_22px_-4px_rgba(93,96,127,0.2)] max-md:mx-auto">
          <form class="space-y-4" method="POST">
            {% csrf_token %}
            <div class="mb-8">
              <h3 class="text-gray-800 text-3xl font-extrabold">Crea una Cuenta</h3>
            </div>

            <div>
              <label for="id_username" class="text-gray-800 text-sm mb-2 block">Usuario</label>
              {% for error in form.username.errors %}
                  <div class="my-2 text-xs text-red-700 font-medium block">
                      <span>{{ error }}</span><br>
                  </div>
              {% endfor %}
              <div class="relative flex items-center">
                {{ form.username|add_class:"w-full text-sm text-gray-800 border border-gray-300 px-4 py-3 rounded-lg outline-blue-600" }}
                {% comment %} <svg xmlns="http://www.w3.org/2000/svg" fill="#bbb" stroke="#bbb" class="w-[18px] h-[18px] absolute right-4" viewBox="0 0 24 24">
                  <circle cx="10" cy="7" r="6" data-original="#000000"></circle>
                  <path d="M14 15H6a5 5 0 0 0-5 5 3 3 0 0 0 3 3h12a3 3 0 0 0 3-3 5 5 0 0 0-5-5zm8-4h-2.59l.3-.29a1 1 0 0 0-1.42-1.42l-2 2a1 1 0 0 0 0 1.42l2 2a1 1 0 0 0 1.42 0 1 1 0 0 0 0-1.42l-.3-.29H22a1 1 0 0 0 0-2z" data-original="#000000"></path>
                </svg> {% endcomment %}
              </div>
            </div>
            <div>
              <label for="id_password1" class="text-gray-800 text-sm mb-2 block">Contraseña</label>
              {% for error in form.password1.errors %}
                  <div class="my-2 text-xs text-red-700 font-medium block">
                      <span>{{ error }}</span><br>
                  </div>
              {% endfor %}
              <div class="relative flex items-center">
                {{ form.password1|add_class:"w-full text-sm text-gray-800 border border-gray-300 px-4 py-3 rounded-lg outline-blue-600" }}
                {% comment %} <svg xmlns="http://www.w3.org/2000/svg" fill="#bbb" stroke="#bbb" class="w-[18px] h-[18px] absolute right-4 cursor-pointer" viewBox="0 0 128 128">
                  <path d="M64 104C22.127 104 1.367 67.496.504 65.943a4 4 0 0 1 0-3.887C1.367 60.504 22.127 24 64 24s62.633 36.504 63.496 38.057a4 4 0 0 1 0 3.887C126.633 67.496 105.873 104 64 104zM8.707 63.994C13.465 71.205 32.146 96 64 96c31.955 0 50.553-24.775 55.293-31.994C114.535 56.795 95.854 32 64 32 32.045 32 13.447 56.775 8.707 63.994zM64 88c-13.234 0-24-10.766-24-24s10.766-24 24-24 24 10.766 24 24-10.766 24-24 24zm0-40c-8.822 0-16 7.178-16 16s7.178 16 16 16 16-7.178 16-16-7.178-16-16-16z" data-original="#000000"></path>
                </svg> {% endcomment %}
              </div>
            </div>

            <div>
              <label for="id_password2" class="text-gray-800 text-sm mb-2 block">Confirmar Contraseña</label>
              {% for error in form.password2.errors %}
                  <div class="my-2 text-xs text-red-700 font-medium block">
                      <span>{{ error }}</span><br>
                  </div>
              {% endfor %}
              <div class="relative flex items-center">
                {{ form.password2|add_class:"w-full text-sm text-gray-800 border border-gray-300 px-4 py-3 rounded-lg outline-blue-600" }}
                {% comment %} <svg xmlns="http://www.w3.org/2000/svg" fill="#bbb" stroke="#bbb" class="w-[18px] h-[18px] absolute right-4 cursor-pointer" viewBox="0 0 128 128">
                  <path d="M64 104C22.127 104 1.367 67.496.504 65.943a4 4 0 0 1 0-3.887C1.367 60.504 22.127 24 64 24s62.633 36.504 63.496 38.057a4 4 0 0 1 0 3.887C126.633 67.496 105.873 104 64 104zM8.707 63.994C13.465 71.205 32.146 96 64 96c31.955 0 50.553-24.775 55.293-31.994C114.535 56.795 95.854 32 64 32 32.045 32 13.447 56.775 8.707 63.994zM64 88c-13.234 0-24-10.766-24-24s10.766-24 24-24 24 10.766 24 24-10.766 24-24 24zm0-40c-8.822 0-16 7.178-16 16s7.178 16 16 16 16-7.178 16-16-7.178-16-16-16z" data-original="#000000"></path>
                </svg> {% endcomment %}
              </div>
            </div>

            <div class="!mt-8">
              <button type="submit" class="w-full shadow-xl py-3 px-4 text-sm tracking-wide rounded-lg text-white bg-blue-600 hover:bg-blue-700 focus:outline-none">
                Crear Cuenta
              </button>
            </div>

            <p class="text-sm !mt-8 text-center text-gray-800">Ya tienes cuenta? <a href="{% url 'users:login' %}" class="text-blue-600 font-semibold hover:underline ml-1 whitespace-nowrap">Ingresar a cuenta</a></p>
          </form>
        </div>
        <div class="md:block hidden lg:h-[400px] md:h-[300px] max-md:mt-8">
          <img src="{% static 'images/register.png' %}" class="w-full h-full max-md:w-4/5 mx-auto block object-cover" alt="Dining Experience" />
        </div>
      </div>
    </div>
  </div>

{% endblock content %}